#spring.mongodb.uri=mongodb+srv://animeshjojo:Wb0UB9jfipuxNXgA@cluster0.smqbtnc.mongodb.net/?appName=Cluster0
#spring.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#spring.main.allow-circular-references = true
spring:
  mongodb:
    uri: mongodb+srv://animeshjojo:Wb0UB9jfipuxNXgA@cluster0.smqbtnc.mongodb.net/?appName=Cluster0
    database: journaldb
  data:
    mongodb:
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
  port: 8080
  servlet:
    context=path: /app


#logging:
 # level:
  #  com:
   #   animesh:
    #    journal: debug

#logging:
  #level:
    #root or package name: off   It turns of all log for particular package or whole root appliaction

# severity of logging->  Low to high
# Trace-> Debug -> Info -> Warn -> Error