spring:
  mongodb:
    uri: mongodb+srv://animeshjojo:Wb0UB9jfipuxNXgA@cluster0.smqbtnc.mongodb.net/?appName=Cluster0
    database: journaldb
  data:
    mongodb:
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
  port: 8080
  servlet:
    context=path: /app


