#spring.mongodb.uri=mongodb+srv://animeshjojo:Wb0UB9jfipuxNXgA@cluster0.smqbtnc.mongodb.net/?appName=Cluster0
#spring.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#spring.main.allow-circular-references = true
spring:
  profiles:
    active: dev


